[package]
name = "rugo"
description = "A cache server with the throughput of a hand-written one and half the memory."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
rugo-server.workspace = true

[lints]
workspace = true
