[package]
name = "rugo-server"
description = "The rugo cache server: listeners, threads, and the command set."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
rugo-map.workspace = true
rugo-net.workspace = true
rugo-resp.workspace = true

[lints]
workspace = true
